KursachOliaMarina/Controllers/AdminsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KursachOliaMarina.Models;

namespace KursachOliaMarina.Controllers
{
    public class AdminsController : Controller
    {
        private CanteenContext db = new CanteenContext();

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(Admin admin)
        {
            List<Admin> adminRes = db.Admins.Where(adm => adm.Login.Equals(admin.Login) && adm.Password.Equals(admin.Password)).ToList();
            if (adminRes.Count == 1)
            {
                Session["admin"] = adminRes.First();
                ViewBag.LoginAdmin = ((Admin)Session["admin"]).Login;
                return RedirectToAction("Index");
            }
            ViewBag.LoginFaultMessage = "Не верная пара логин/пароль";
            return View("Login");

        }
        [HttpGet]
        public ActionResult Logout()
        {
            Session["admin"] = null;
            return RedirectToAction("Index", "Home");
        }

        // GET: Admins
        public ActionResult Index()
        {
            if (Session["admin"] == null)
            {
                ViewBag.LoginFaultMessage = "Ошибка доступа. Авторизируйтесь";
                return RedirectToAction("Login");
            }
            ViewBag.LoginAdmin = ((Admin)Session["admin"]).Login;
            //int hc = db.Hairdressers.Count();
            //ViewBag.HairdressersCount = hc;
            //GetDataForAdmin();
            //ViewBag.UsersCount = db.Users.Count();
            //ViewBag.IngredientsCount = db.Ingredients.Count();
            //ViewBag.DishesCount = db.Dishes.Count();
            //ViewBag.DishesCount = db.Dishes.Count();
            return View();
        }
        public ActionResult Users()
        {
            if (Session["admin"] == null)
            {
                ViewBag.LoginFaultMessage = "Ошибка доступа. Авторизируйтесь";
                return RedirectToAction("Login");
            }
            ViewBag.LoginAdmin = ((Admin)Session["admin"]).Login;
            return RedirectToAction("Index", "Users");
        }
        public ActionResult DeleteUser(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            db.Users.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Users");
        }
        public ActionResult DetailsUser(int? id)
        {
            if (Session["admin"] == null)
            {
                ViewBag.LoginFaultMessage = "Ошибка доступа. Авторизируйтесь";
                return RedirectToAction("Login");
            }
            return RedirectToAction("Details","Users");
        }














        public ActionResult CreateIngredient([Bind(Include = "Id,IngredientName")] Ingredient ingredient)
        {
            if (ModelState.IsValid)
            {
                // db.Ingredients.Add(ingredient);
                // db.SaveChanges();
            }
            return RedirectToAction("Create", "Ingredients");
        }

        public ActionResult Ingredients()
        {
            if (Session["admin"] == null)
            {
                ViewBag.LoginFaultMessage = "Ошибка доступа. Авторизируйтесь";
                return RedirectToAction("Login");
            }
            ViewBag.LoginAdmin = ((Admin)Session["admin"]).Login;
            return RedirectToAction("Index", "Ingredients");

        }
        public ActionResult DeleteIngredient(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ingredient ingredient = db.Ingredients.Find(id);
            if (ingredient == null)
            {
                return HttpNotFound();
            }
            db.Ingredients.Remove(ingredient);
            db.SaveChanges();
            return RedirectToAction("Ingredients");
        }




        public ActionResult Dishes()
        {
            if (Session["admin"] == null)
            {
                ViewBag.LoginFaultMessage = "Ошибка доступа. Авторизируйтесь";
                return RedirectToAction("Login");
            }
            ViewBag.LoginAdmin = ((Admin)Session["admin"]).Login;
            return RedirectToAction("Index", "Dishes");
        }

        public ActionResult DetailsDish()
        {
            if (ModelState.IsValid)
            {
               // int idCurrentMenu = (from m in db.Menus select m.Id).ToList().Last();
                return RedirectToAction("Details", "Dishes");
                // db.Dishes.Add(dish);
                // db.SaveChanges();
            }
            return RedirectToAction("Dishes");
        }
        public ActionResult CreateDish([Bind(Include = "Id,DishName,Category,Price,Weight,Note")] Dish dish)
        {
            if (ModelState.IsValid)
            {
                
                // db.Dishes.Add(dish);
                // db.SaveChanges();
            }
            return RedirectToAction("Create", "Dishes");
        }

        public ActionResult EditDish([Bind(Include = "Id,DishName,Category,Price,Weight,Note")] Dish dish)
        {
            if (ModelState.IsValid)
            {
                return RedirectToAction("Edit", "Dishes");
                // db.Dishes.Add(dish);
                // db.SaveChanges();
            }
            return RedirectToAction("Dishes");
        }

        public ActionResult DeleteDish(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dish dish = db.Dishes.Find(id);
            if (dish == null)
            {
                return HttpNotFound();
            }
            db.Dishes.Remove(dish);
            db.SaveChanges();
            return RedirectToAction("Dishes");
        }




        public ActionResult CreateMenu()
        {
            if (Session["admin"] == null)
            {
                ViewBag.LoginFaultMessage = "Ошибка доступа. Авторизируйтесь";
                return RedirectToAction("Login");
            }
            ViewBag.LoginAdmin = ((Admin)Session["admin"]).Login;
            GetDataForAdmin();
            return View();
        }
        public ActionResult Menus()
        {
            if (Session["admin"] == null)
            {
                ViewBag.LoginFaultMessage = "Ошибка доступа. Авторизируйтесь";
                return RedirectToAction("Login");
            }
            ViewBag.LoginAdmin = ((Admin)Session["admin"]).Login;
            return RedirectToAction("Index", "Menus");
        }

        public void GetDataForAdmin()
        {
            Admin admin = (Admin)Session["admin"];
            IEnumerable<Dish> dishes = db.Dishes;
            ViewBag.Dishes = dishes;
            ViewBag.IdAdmin = admin.Id;
            IList<Menu> menus = db.Menus.Where(f => f.Id.Equals(admin.Id)).ToList();
            IList<List<Dish>> selectedDishes = new List<List<Dish>>();

            foreach (Menu menu in menus)
            {

                selectedDishes.Add(menu.Dishes.ToList());

            }

            ViewBag.SelectedDishes = selectedDishes;
        }

      

        public ActionResult CreateAdditionMenu([Bind(Include = "Id,dateOfMenu")] Menu menu)
        {
            if (ModelState.IsValid)
            {
                db.Menus.Add(menu);
                db.SaveChanges();
            }
            return RedirectToAction("Menus");
        }
        
       
      
       

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

KursachOliaMarina/Controllers/MenusController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KursachOliaMarina.Models;

namespace KursachOliaMarina.Controllers
{
    public class MenusController : Controller
    {
        private CanteenContext db = new CanteenContext();

        // GET: Menus
        public ActionResult Index()
        {
            var menus = db.Menus.Include(m => m.Admin);
            return View(menus.ToList());
        }

        // GET: Menus/Details/5
        public ActionResult Details()
        {
            int? id = (from m in db.Menus select m.Id).ToList().Last();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Menu menu = db.Menus.Find(id);
            if (menu == null)
            {
                return HttpNotFound();
            }
            return View(menu);
        }

        public ActionResult CurrentMenu()
        {
            DateTime dayOfWeek = DateTime.Today;

            Menu menuForToday = db.Menus.Where(f => f.DateOfMenu.Equals(dayOfWeek)).First();

            IList<Dish> selectedDishes = new List<Dish>();

            foreach (Dish dish in menuForToday.Dishes)
            {
                selectedDishes.Add(dish);
            }
            
            ViewBag.SelectedDishes = selectedDishes;
        
            return View();

        }

        // GET: Menus/Create
        public ActionResult Create()
        {
            ViewBag.AdminId = new SelectList(db.Admins, "Id", "Login");
            return View();
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,DateOfMenu,AdminId")] Menu menu)
        {
            if (ModelState.IsValid)
            {
                db.Menus.Add(menu);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.AdminId = new SelectList(db.Admins, "Id", "Login", menu.AdminId);
            return View(menu);
        }

        // GET: Menus/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Menu menu = db.Menus.Find(id);
            if (menu == null)
            {
                return HttpNotFound();
            }
            ViewBag.AdminId = new SelectList(db.Admins, "Id", "Login", menu.AdminId);
            return View(menu);
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,DateOfMenu,AdminId")] Menu menu)
        {
            if (ModelState.IsValid)
            {
                db.Entry(menu).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AdminId = new SelectList(db.Admins, "Id", "Login", menu.AdminId);
            return View(menu);
        }

        // GET: Menus/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Menu menu = db.Menus.Find(id);
            if (menu == null)
            {
                return HttpNotFound();
            }
            return View(menu);
        }

        // POST: Menus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Menu menu = db.Menus.Find(id);
            db.Menus.Remove(menu);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

KursachOliaMarina/Controllers/ZakazsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KursachOliaMarina.Models;

namespace KursachOliaMarina.Controllers
{
    public class ZakazsController : Controller
    {
        private CanteenContext db = new CanteenContext();

        // GET: Zakazs
        public ActionResult Index()
        {
            var zakazs = db.Zakazs.Include(z => z.User);
            return View(zakazs.ToList());
        }

        // GET: Zakazs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Zakaz zakaz = db.Zakazs.Find(id);
            if (zakaz == null)
            {
                return HttpNotFound();
            }
            return View(zakaz);
        }

        // GET: Zakazs/Create
        public ActionResult Create()
        {
            ViewBag.UserId = new SelectList(db.Users, "Id", "Email");
            return View();
        }

        // POST: Zakazs/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,DateOfZakaz,UserId")] Zakaz zakaz)
        {
            if (ModelState.IsValid)
            {
                db.Zakazs.Add(zakaz);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UserId = new SelectList(db.Users, "Id", "Email", zakaz.UserId);
            return View(zakaz);
        }

        // GET: Zakazs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Zakaz zakaz = db.Zakazs.Find(id);
            if (zakaz == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserId = new SelectList(db.Users, "Id", "Email", zakaz.UserId);
            return View(zakaz);
        }

        // POST: Zakazs/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,DateOfZakaz,UserId")] Zakaz zakaz)
        {
            if (ModelState.IsValid)
            {
                db.Entry(zakaz).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserId = new SelectList(db.Users, "Id", "Email", zakaz.UserId);
            return View(zakaz);
        }

        // GET: Zakazs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Zakaz zakaz = db.Zakazs.Find(id);
            if (zakaz == null)
            {
                return HttpNotFound();
            }
            return View(zakaz);
        }

        // POST: Zakazs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Zakaz zakaz = db.Zakazs.Find(id);
            db.Zakazs.Remove(zakaz);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

KursachOliaMarina/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                   
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                    <a class="dropdown-toggle" role="button" aria-expanded="false" href="#" data-toggle="dropdown">Войти на сайт<span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        <li>@Html.ActionLink("Клиент", "LoginUser", "Users")</li>
                        <li>@Html.ActionLink("Админ", "Login", "Admins")</li>
                    </ul>
                </li>
                <li>@Html.ActionLink("Зарегистрироваться", "Index", "Registration")</li></a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year – приложение ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

KursachOliaMarina/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
               
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                   

                </ul>
                 <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                    <a class="dropdown-toggle" role="button" aria-expanded="false" href="#" data-toggle="dropdown">Личный кабинет <span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        <li>@Html.ActionLink("Блюда", "Index", "Dishes")</li>
                        <li>@Html.ActionLink("Ингредиенты", "Index", "Ingredients")</li>
                        <li>@Html.ActionLink("Клиенты", "Index", "Users")</li>
                        <li>@Html.ActionLink("Меню", "Index", "Menus")</li>
                    </ul>
                </li>
                <li><a id = "text-menu" href="/Admins/Logout">Выход </a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year – приложение ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

KursachOliaMarina/Views/Shared/_LayoutUser.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                   
                </ul>
                 <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                    <a class="dropdown-toggle" role="button" aria-expanded="false" href="#" data-toggle="dropdown">Личный кабинет <span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("Мои заказы", "Index", "Zakazs")</li>
                            <li>@Html.ActionLink("Информация", "Details", "Users", new { id = 1 }, null)</li>
                        </ul>
                    </li>
                    <li><a id = "text-menu" href="/Users/LogoutUser">Выход </a></li>
                </ul>
                
            </div> 
                </ul>

            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>